import { PYTHON_VERSIONS } from '../../../../versions.js';
export const generatePyprojectToml = (params) => {
    const { config } = params;
    // Format Python versions with >= prefix for TOML
    const formatPythonVersion = (version) => {
        // Remove >= prefix if present, then add it back
        const cleanVersion = version.replace(/^>=/, '');
        return `>=${cleanVersion}`;
    };
    const dbDeps = config.features.db
        ? `    "sqlalchemy${formatPythonVersion(PYTHON_VERSIONS.sqlalchemy)}",
    "alembic${formatPythonVersion(PYTHON_VERSIONS.alembic)}",
    "asyncpg${formatPythonVersion(PYTHON_VERSIONS.asyncpg)}",
    "greenlet${formatPythonVersion(PYTHON_VERSIONS.greenlet)}",
    `
        : '';
    const dbLocalDeps = config.features.db
        ? `
    "${config.name}-db",`
        : '';
    const uvSources = config.features.db
        ? `

[tool.uv.sources]
"${config.name}-db" = { path = "../db", editable = true }`
        : '';
    const pythonVersion = formatPythonVersion(PYTHON_VERSIONS.python);
    return /* toml */ `[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "api"
dynamic = ["version"]
description = "FastAPI backend application"
requires-python = "${pythonVersion}"
license = "MIT"
authors = [
    { name = "Generated by AI QuickStart CLI" },
]
dependencies = [
    "fastapi${formatPythonVersion(PYTHON_VERSIONS.fastapi)}",
    "uvicorn[standard]${formatPythonVersion(PYTHON_VERSIONS.uvicorn)}",
    "pydantic${formatPythonVersion(PYTHON_VERSIONS.pydantic)}",
    "pydantic-settings${formatPythonVersion(PYTHON_VERSIONS['pydantic-settings'])}",
${dbDeps}${dbLocalDeps}
]

[project.optional-dependencies]
dev = [
    "pytest${formatPythonVersion(PYTHON_VERSIONS.pytest)}",
    "pytest-asyncio${formatPythonVersion(PYTHON_VERSIONS['pytest-asyncio'])}",
    "httpx${formatPythonVersion(PYTHON_VERSIONS.httpx)}",
    "ruff${formatPythonVersion(PYTHON_VERSIONS.ruff)}",
    "mypy${formatPythonVersion(PYTHON_VERSIONS.mypy)}",
]

[project.urls]
Homepage = "https://github.com/example/${config.name}"
Repository = "https://github.com/example/${config.name}.git"

[tool.hatch.version]
path = "src/__init__.py"${config.features.db
        ? `

[tool.hatch.metadata]
allow-direct-references = true`
        : ''}

[tool.ruff]
extend = "../../configs/ruff/pyproject.toml"

[tool.mypy]
python_version = "${PYTHON_VERSIONS.python.replace(/^>=/, '')}"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false
ignore_missing_imports = true

[tool.hatch.build.targets.wheel]
packages = ["src"]${uvSources}
`;
};
