export const generatePyprojectToml = (params) => {
    const { config } = params;
    const dbDeps = config.features.db
        ? `    "sqlalchemy>=2.0.0",
    "alembic>=1.13.0",
    "asyncpg>=0.29.0",
    "greenlet>=3.2.3",
    `
        : '';
    const dbLocalDeps = config.features.db
        ? `
    "${config.name}-db",`
        : '';
    const uvSources = config.features.db
        ? `

[tool.uv.sources]
"${config.name}-db" = { path = "../db", editable = true }`
        : '';
    return `[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "api"
dynamic = ["version"]
description = "FastAPI backend application"
requires-python = ">=3.11"
license = "MIT"
authors = [
    { name = "Generated by AI Kickstart" },
]
dependencies = [
    "fastapi>=0.104.0",
    "uvicorn[standard]>=0.24.0",
    "pydantic>=2.5.0",
    "pydantic-settings>=2.1.0",
${dbDeps}${dbLocalDeps}
]

[project.optional-dependencies]
dev = [
    "pytest>=7.4.0",
    "pytest-asyncio>=0.21.0",
    "httpx>=0.25.0",
    "ruff>=0.1.0",
    "mypy>=1.7.0",
]

[project.urls]
Homepage = "https://github.com/example/${config.name}"
Repository = "https://github.com/example/${config.name}.git"

[tool.hatch.version]
path = "src/__init__.py"${config.features.db
        ? `

[tool.hatch.metadata]
allow-direct-references = true`
        : ''}

[tool.ruff]
extend = "../../configs/ruff/pyproject.toml"

[tool.hatch.build.targets.wheel]
packages = ["src"]${uvSources}
`;
};
