import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from 'react';
import { Box, Text, useApp } from 'ink';
import BigText from 'ink-big-text';
import Gradient from 'ink-gradient';
export function SuccessMessage({ projectPath, projectName }) {
    const { exit } = useApp();
    // Exit after render completes - message stays in terminal history
    React.useEffect(() => {
        exit();
    }, [exit]);
    return (_jsxs(Box, { flexDirection: "column", alignItems: "center", paddingX: 2, children: [_jsx(Gradient, { name: "rainbow", children: _jsx(BigText, { text: "Success!", font: "block" }) }), _jsxs(Box, { flexDirection: "column", borderStyle: "round", borderColor: "green", padding: 1, width: 60, children: [_jsx(Text, { color: "gray", children: "Your kickstart is ready!" }), _jsxs(Text, { children: ["\uD83D\uDCC1 Location: ", _jsx(Text, { color: "cyan", children: projectPath })] }), _jsx(Box, { marginTop: 1, children: _jsx(Text, { color: "green", bold: true, children: "\uD83D\uDE80 Next Steps:" }) }), _jsxs(Box, { flexDirection: "column", marginTop: 1, children: [_jsxs(Box, { flexDirection: "row", marginLeft: 1, children: [_jsx(Text, { color: "yellow", children: "1." }), _jsx(Box, { marginLeft: 1, children: _jsxs(Text, { children: [_jsx(Text, { color: "cyan", children: "cd" }), " ", _jsx(Text, { color: "white", children: projectName })] }) })] }), _jsxs(Box, { flexDirection: "row", marginLeft: 1, children: [_jsx(Text, { color: "yellow", children: "2." }), _jsx(Box, { marginLeft: 1, children: _jsxs(Text, { children: [_jsx(Text, { color: "cyan", children: "pnpm" }), " ", _jsx(Text, { color: "blue", children: "dev" })] }) })] })] }), _jsx(Box, { marginTop: 1, borderStyle: "single", borderColor: "blue", paddingX: 1, children: _jsxs(Box, { alignItems: "flex-start", flexDirection: "column", children: [_jsx(Text, { color: "blue", bold: true, children: "\uD83D\uDCA1 Quick Tips:" }), _jsxs(Text, { children: ["\u2022 Check ", _jsx(Text, { color: "cyan", children: "README.md" })] }), _jsxs(Text, { children: ["\u2022 ", _jsx(Text, { color: "cyan", children: "pnpm" }), " ", _jsx(Text, { color: "blue", children: "build" }), " for production"] }), _jsxs(Text, { children: ["\u2022 ", _jsx(Text, { color: "cyan", children: "pnpm" }), " ", _jsx(Text, { color: "blue", children: "test" }), " to run test suites"] }), _jsxs(Text, { children: ["\u2022 Customize in ", _jsx(Text, { color: "cyan", children: "packages/" })] })] }) }), _jsx(Box, { marginTop: 1, children: _jsx(Text, { color: "gray", children: "Happy coding! \uD83D\uDE80 Visit https://github.com/your-org/ai-kickstart for docs." }) })] })] }));
}
